trigger:
  batch: true
  branches:
    include:
    - master
    - develop

variables:
- name: EOCompliance-Mac
  value: true

pr:
- master
- develop

jobs:
- job:
  strategy:
    matrix:
      Mojave:
        IMAGE_POOL: 'macOS-11'
      # Android Emulator is not available on Ubuntu
      # Ubuntu-16:
      # IMAGE_POOL: 'ubuntu-16.04'
  pool:
    vmImage: $(IMAGE_POOL)

  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: 'server/'
      gradleWrapperFile: 'server/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      tasks: 'assembleAndroidTest'
      displayName: "Build TestServer.apk"

  - script: bin/ci/ado/install-android-sdk.sh
    displayName: "Install Android Sdk"

  - script: bin/ci/ado/start-emulator.sh
    displayName: "Start Emulator"

  # TODO: publish cucumber report
  # - server/integration-tests/test-report/*.xml
  - script: |
      cd server/integration-tests
      ./test.sh --skip-build
    displayName: "$(IMAGE_POOL) - Integration Tests"
